#ifndef RT_CONFIG_H__
#define RT_CONFIG_H__

/* Generated by Kconfiglib (https://github.com/ulfalizer/Kconfiglib) */

/* RT-Thread Kernel */

#define RT_NAME_MAX 8
#define RT_ALIGN_SIZE 4
#define RT_THREAD_PRIORITY_32
#define RT_THREAD_PRIORITY_MAX 32
#define RT_TICK_PER_SECOND 1000
#define RT_USING_OVERFLOW_CHECK
#define RT_USING_HOOK
#define RT_USING_IDLE_HOOK
#define RT_IDLE_HOOK_LIST_SIZE 4
#define IDLE_THREAD_STACK_SIZE 256
#define RT_USING_TIMER_SOFT
#define RT_TIMER_THREAD_PRIO 4
#define RT_TIMER_THREAD_STACK_SIZE 512
#define RT_DEBUG
#define RT_DEBUG_COLOR

/* Inter-Thread communication */

#define RT_USING_SEMAPHORE
#define RT_USING_MUTEX
#define RT_USING_EVENT
#define RT_USING_MAILBOX
#define RT_USING_MESSAGEQUEUE
/* end of Inter-Thread communication */

/* Memory Management */

#define RT_USING_MEMPOOL
#define RT_USING_SMALL_MEM
#define RT_USING_HEAP
/* end of Memory Management */

/* Kernel Device Object */

#define RT_USING_DEVICE
#define RT_USING_CONSOLE
#define RT_CONSOLEBUF_SIZE 256
#define RT_CONSOLE_DEVICE_NAME "uart1"
/* end of Kernel Device Object */
#define RT_VER_NUM 0x40003
/* end of RT-Thread Kernel */
#define ARCH_ARM
#define RT_USING_CPU_FFS
#define ARCH_ARM_CORTEX_M
#define ARCH_ARM_CORTEX_M3

/* RT-Thread Components */

#define RT_USING_COMPONENTS_INIT
#define RT_USING_USER_MAIN
#define RT_MAIN_THREAD_STACK_SIZE 2048
#define RT_MAIN_THREAD_PRIORITY 10

/* C++ features */

/* end of C++ features */

/* Command shell */

#define RT_USING_FINSH
#define FINSH_THREAD_NAME "tshell"
#define FINSH_USING_HISTORY
#define FINSH_HISTORY_LINES 5
#define FINSH_USING_SYMTAB
#define FINSH_USING_DESCRIPTION
#define FINSH_THREAD_PRIORITY 20
#define FINSH_THREAD_STACK_SIZE 4096
#define FINSH_CMD_SIZE 80
#define FINSH_USING_MSH
#define FINSH_USING_MSH_DEFAULT
#define FINSH_USING_MSH_ONLY
#define FINSH_ARG_MAX 10
/* end of Command shell */

/* Device virtual file system */

/* end of Device virtual file system */

/* Device Drivers */

#define RT_USING_DEVICE_IPC
#define RT_PIPE_BUFSZ 512
#define RT_USING_SERIAL
#define RT_SERIAL_RB_BUFSZ 64
#define RT_USING_PIN

/* Using USB */

/* end of Using USB */
/* end of Device Drivers */

/* POSIX layer and C standard library */

#define RT_LIBC_USING_TIME
/* end of POSIX layer and C standard library */

/* Network */

/* Socket abstraction layer */

/* end of Socket abstraction layer */

/* Network interface device */

/* end of Network interface device */

/* light weight TCP/IP stack */

/* end of light weight TCP/IP stack */

/* AT commands */

/* end of AT commands */
/* end of Network */

/* VBUS(Virtual Software BUS) */

/* end of VBUS(Virtual Software BUS) */

/* Utilities */

/* end of Utilities */
/* end of RT-Thread Components */

/* RT-Thread online packages */

/* IoT - internet of things */

#define PKG_USING_FREEMODBUS
#define PKG_FREEMODBUS_VERSION "latest"
/* #define PKG_MODBUS_MASTER_RTU */
#define PKG_MODBUS_SLAVE
/* #define PKG_MODBUS_MASTER_RTU_AND_SLAVE */
#define PKG_MODBUS_SLAVE_RTU
/* #define PKG_MODBUS_SLAVE_ASCII */
/* #define PKG_MODBUS_SLAVE_TCP */
/* #define PKG_MODBUS_SLAVE_SAMPLE */

/*
 * FreeModbus register map for 快检设备 protocol
 * Register addresses (1-based):
 *   00001~00033  - 功能/状态区 (Function/Status)
 *   00100~00104  - 实时数据 (Real-time Data)
 *   00120~00198  - 参数设置 (Parameter Settings)
 */
#define RT_S_DISCRETE_INPUT_START      0
#define RT_S_DISCRETE_INPUT_NDISCRETES 0
#define RT_S_COIL_START                0
#define RT_S_COIL_NCOILS               0
#define RT_S_REG_INPUT_START           0
#define RT_S_REG_INPUT_NREGS           0
#define RT_S_REG_HOLDING_START         0
#define RT_S_REG_HOLDING_NREGS         200   /* 1~198 + margin */
#define RT_S_HD_RESERVE                0
#define RT_S_IN_RESERVE                0
#define RT_S_CO_RESERVE                0
#define RT_S_DI_RESERVE                0

/*
 * ═══════════════════════════════════════════════════════════════════
 *  Application Config — CANopen Master + Modbus Gateway
 * ═══════════════════════════════════════════════════════════════════
 */

/* CANopen: master node ID (1~127) */
#define CONFIG_CANOPEN_MASTER_NODE_ID   0x01
/* CANopen: target slave node ID (1~127) */
#define CONFIG_CANOPEN_SLAVE_NODE_ID    0x02
/* CANopen: bit rate for CAN1 (kbps) */
#define CONFIG_CANOPEN_BAUD_RATE_K      50

/* Modbus Slave: RTU address (1~247) */
#define CONFIG_MODBUS_SLAVE_ADDR        1
/* Modbus Slave: UART port number (1=UART1, 2=UART2) */
#define CONFIG_MODBUS_SERIAL_PORT       2
/* Modbus Slave: baud rate */
#define CONFIG_MODBUS_BAUD_RATE         115200
/* Modbus Slave: parity (MB_PAR_NONE / MB_PAR_ODD / MB_PAR_EVEN) */
#define CONFIG_MODBUS_PARITY            MB_PAR_NONE

/* SDO transaction timeout (ms) per transfer */
#define CONFIG_SDO_TIMEOUT_MS           500
/* SDO polling interval (ms) */
#define CONFIG_SDO_POLL_INTERVAL_MS     20

/* FreeModbus register map for Master mode (kept for compilation) */
#define RT_M_DISCRETE_INPUT_START      0
#define RT_M_DISCRETE_INPUT_NDISCRETES 16
#define RT_M_COIL_START                0
#define RT_M_COIL_NCOILS               16
#define RT_M_REG_INPUT_START           0
#define RT_M_REG_INPUT_NREGS           100
#define RT_M_REG_HOLDING_START         0
#define RT_M_REG_HOLDING_NREGS         100
#define RT_M_HD_RESERVE                0
#define RT_M_IN_RESERVE                0
#define RT_M_CO_RESERVE                0
#define RT_M_DI_RESERVE                0

/* Wi-Fi */

/* Marvell WiFi */

/* end of Marvell WiFi */

/* Wiced WiFi */

/* end of Wiced WiFi */
/* end of Wi-Fi */

/* IoT Cloud */

/* end of IoT Cloud */
/* end of IoT - internet of things */

/* security packages */

/* end of security packages */

/* language packages */

/* JSON: JavaScript Object Notation, a lightweight data-interchange format */

/* end of JSON: JavaScript Object Notation, a lightweight data-interchange format */

/* XML: Extensible Markup Language */

/* end of XML: Extensible Markup Language */
/* end of language packages */

/* multimedia packages */

/* LVGL: powerful and easy-to-use embedded GUI library */

/* end of LVGL: powerful and easy-to-use embedded GUI library */

/* u8g2: a monochrome graphic library */

/* end of u8g2: a monochrome graphic library */

/* PainterEngine: A cross-platform graphics application framework written in C language */

/* end of PainterEngine: A cross-platform graphics application framework written in C language */
/* end of multimedia packages */

/* tools packages */

/* end of tools packages */

/* system packages */

/* enhanced kernel services */

/* end of enhanced kernel services */

/* acceleration: Assembly language or algorithmic acceleration packages */

/* end of acceleration: Assembly language or algorithmic acceleration packages */

/* CMSIS: ARM Cortex-M Microcontroller Software Interface Standard */

/* end of CMSIS: ARM Cortex-M Microcontroller Software Interface Standard */

/* Micrium: Micrium software products porting for RT-Thread */

/* end of Micrium: Micrium software products porting for RT-Thread */
/* end of system packages */

/* peripheral libraries and drivers */


/* Kendryte SDK */

/* end of Kendryte SDK */
/* end of peripheral libraries and drivers */

/* AI packages */

/* end of AI packages */

/* miscellaneous packages */

/* project laboratory */

/* end of project laboratory */

/* samples: kernel and components samples */

/* end of samples: kernel and components samples */

/* entertainment: terminal games and other interesting software packages */

/* end of entertainment: terminal games and other interesting software packages */
/* end of miscellaneous packages */

/* Arduino libraries */


/* Projects */

/* end of Projects */

/* Sensors */

/* end of Sensors */

/* Display */

/* end of Display */

/* Timing */

/* end of Timing */

/* Data Processing */

/* end of Data Processing */

/* Data Storage */

/* Communication */

/* Device Control */

/* end of Device Control */

/* Other */

/* Signal IO */

/* end of Signal IO */

/* Uncategorized */

/* end of Arduino libraries */
/* end of RT-Thread online packages */

/* samples: kernel and components samples */

/* end of samples: kernel and components samples */
#define RT_STUDIO_BUILT_IN

#endif
