
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MASTER_H
#define MASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data Master_Data;
extern INTEGER8 mX_modes;		/* Mapped at index 0x2001, subindex 0x00*/
extern INTEGER32 mX_position;		/* Mapped at index 0x2002, subindex 0x00*/
extern INTEGER32 mX_velocity;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS16 mX_status_word;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS16 mX_control_word;		/* Mapped at index 0x2005, subindex 0x00*/
extern INTEGER8 mY_modes;		/* Mapped at index 0x2006, subindex 0x00*/
extern INTEGER32 mY_position;		/* Mapped at index 0x2007, subindex 0x00*/
extern INTEGER32 mY_velocity;		/* Mapped at index 0x2008, subindex 0x00*/
extern UNS16 mY_status_word;		/* Mapped at index 0x2009, subindex 0x00*/
extern UNS16 mY_control_word;		/* Mapped at index 0x200A, subindex 0x00*/
extern INTEGER8 mZ_modes;		/* Mapped at index 0x200B, subindex 0x00*/
extern INTEGER32 mZ_position;		/* Mapped at index 0x200C, subindex 0x00*/
extern INTEGER32 mZ_velocity;		/* Mapped at index 0x200D, subindex 0x00*/
extern UNS16 mZ_status_word;		/* Mapped at index 0x200E, subindex 0x00*/
extern UNS16 mZ_control_word;		/* Mapped at index 0x200F, subindex 0x00*/
extern INTEGER8 mE_modes;		/* Mapped at index 0x2010, subindex 0x00*/
extern INTEGER32 mE_position;		/* Mapped at index 0x2011, subindex 0x00*/
extern INTEGER32 mE_velocity;		/* Mapped at index 0x2012, subindex 0x00*/
extern UNS16 mE_status_word;		/* Mapped at index 0x2013, subindex 0x00*/
extern UNS16 mE_control_word;		/* Mapped at index 0x2014, subindex 0x00*/
extern INTEGER8 mT_modes;		/* Mapped at index 0x2015, subindex 0x00*/
extern INTEGER32 mT_position;		/* Mapped at index 0x2016, subindex 0x00*/
extern INTEGER32 mT_velocity;		/* Mapped at index 0x2017, subindex 0x00*/
extern UNS16 mT_status_word;		/* Mapped at index 0x2018, subindex 0x00*/
extern UNS16 mT_control_word;		/* Mapped at index 0x2019, subindex 0x00*/
extern UNS16 photometer_ch0;		/* Mapped at index 0x201A, subindex 0x00*/
extern UNS16 photometer_ch1;		/* Mapped at index 0x201B, subindex 0x00*/
extern UNS32 photometer_led;		/* Mapped at index 0x201C, subindex 0x00*/
extern UNS32 TEMP_control_word;		/* Mapped at index 0x201D, subindex 0x00*/
extern UNS32 heating_target;		/* Mapped at index 0x201E, subindex 0x00*/
extern UNS32 refrigeration_target;		/* Mapped at index 0x201F, subindex 0x00*/
extern UNS32 current_heating;		/* Mapped at index 0x2020, subindex 0x00*/
extern UNS32 current_refrigeration;		/* Mapped at index 0x2021, subindex 0x00*/
extern UNS16 photometer_rate;		/* Mapped at index 0x2022, subindex 0x00*/
extern UNS8 photometer_gain;		/* Mapped at index 0x2023, subindex 0x00*/
extern UNS32 TEMP_status_word;		/* Mapped at index 0x2024, subindex 0x00*/
extern INTEGER32 weight_clean_water;		/* Mapped at index 0x2025, subindex 0x00*/
extern INTEGER32 weight_buff_liq;		/* Mapped at index 0x2026, subindex 0x00*/
extern INTEGER32 weight_waste_liq;		/* Mapped at index 0x2027, subindex 0x00*/
extern INTEGER16 mX_Current_actual;		/* Mapped at index 0x2028, subindex 0x00*/
extern INTEGER16 mY_Current_actual;		/* Mapped at index 0x2029, subindex 0x00*/
extern INTEGER16 mZ_Current_actual;		/* Mapped at index 0x202A, subindex 0x00*/
extern INTEGER16 mB_Current_actual;		/* Mapped at index 0x202B, subindex 0x00*/

#endif // MASTER_H
