
/* File generated by gen_cfile.py. Should not be modified. */

#include "ObjDict.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
INTEGER8 mX_modes = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
INTEGER32 mX_position = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
INTEGER32 mX_velocity = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS16 mX_status_word = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */
UNS16 mX_control_word = 0x0;		/* Mapped at index 0x2005, subindex 0x00 */
INTEGER8 mY_modes = 0x0;		/* Mapped at index 0x2006, subindex 0x00 */
INTEGER32 mY_position = 0x0;		/* Mapped at index 0x2007, subindex 0x00 */
INTEGER32 mY_velocity = 0x0;		/* Mapped at index 0x2008, subindex 0x00 */
UNS16 mY_status_word = 0x0;		/* Mapped at index 0x2009, subindex 0x00 */
UNS16 mY_control_word = 0x0;		/* Mapped at index 0x200A, subindex 0x00 */
INTEGER8 mZ_modes = 0x0;		/* Mapped at index 0x200B, subindex 0x00 */
INTEGER32 mZ_position = 0x0;		/* Mapped at index 0x200C, subindex 0x00 */
INTEGER32 mZ_velocity = 0x0;		/* Mapped at index 0x200D, subindex 0x00 */
UNS16 mZ_status_word = 0x0;		/* Mapped at index 0x200E, subindex 0x00 */
UNS16 mZ_control_word = 0x0;		/* Mapped at index 0x200F, subindex 0x00 */
INTEGER8 mE_modes = 0x0;		/* Mapped at index 0x2010, subindex 0x00 */
INTEGER32 mE_position = 0x0;		/* Mapped at index 0x2011, subindex 0x00 */
INTEGER32 mE_velocity = 0x0;		/* Mapped at index 0x2012, subindex 0x00 */
UNS16 mE_status_word = 0x0;		/* Mapped at index 0x2013, subindex 0x00 */
UNS16 mE_control_word = 0x0;		/* Mapped at index 0x2014, subindex 0x00 */
INTEGER8 mT_modes = 0x0;		/* Mapped at index 0x2015, subindex 0x00 */
INTEGER32 mT_position = 0x0;		/* Mapped at index 0x2016, subindex 0x00 */
INTEGER32 mT_velocity = 0x0;		/* Mapped at index 0x2017, subindex 0x00 */
UNS16 mT_status_word = 0x0;		/* Mapped at index 0x2018, subindex 0x00 */
UNS16 mT_control_word = 0x0;		/* Mapped at index 0x2019, subindex 0x00 */
UNS16 photometer_ch0 = 0x0;		/* Mapped at index 0x201A, subindex 0x00 */
UNS16 photometer_ch1 = 0x0;		/* Mapped at index 0x201B, subindex 0x00 */
UNS32 photometer_led = 0x0;		/* Mapped at index 0x201C, subindex 0x00 */
UNS32 TEMP_control_word = 0x0;		/* Mapped at index 0x201D, subindex 0x00 */
UNS32 heating_target = 0x0;		/* Mapped at index 0x201E, subindex 0x00 */
UNS32 refrigeration_target = 0x0;		/* Mapped at index 0x201F, subindex 0x00 */
UNS32 current_heating = 0x0;		/* Mapped at index 0x2020, subindex 0x00 */
UNS32 current_refrigeration = 0x0;		/* Mapped at index 0x2021, subindex 0x00 */
UNS16 photometer_rate = 0x0;		/* Mapped at index 0x2022, subindex 0x00 */
UNS8 photometer_gain = 0x0;		/* Mapped at index 0x2023, subindex 0x00 */
UNS32 TEMP_status_word = 0x0;		/* Mapped at index 0x2024, subindex 0x00 */
INTEGER32 weight_clean_water = 0x0;		/* Mapped at index 0x2025, subindex 0x00 */
INTEGER32 weight_buff_liq = 0x0;		/* Mapped at index 0x2026, subindex 0x00 */
INTEGER32 weight_waste_liq = 0x0;		/* Mapped at index 0x2027, subindex 0x00 */
INTEGER16 mX_Current_actual = 0x0;		/* Mapped at index 0x2028, subindex 0x00 */
INTEGER16 mY_Current_actual = 0x0;		/* Mapped at index 0x2029, subindex 0x00 */
INTEGER16 mZ_Current_actual = 0x0;		/* Mapped at index 0x202A, subindex 0x00 */
INTEGER16 mB_Current_actual = 0x0;		/* Mapped at index 0x202B, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
#define valueRange_1 0xA0 /* Type INTEGER8, 0 < value < 10 */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
    case valueRange_1:
      if (*(INTEGER8*)value < (INTEGER8)0) return OD_VALUE_TOO_LOW;
      if (*(INTEGER8*)value > (INTEGER8)10) return OD_VALUE_TOO_HIGH;
    break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 Master_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 Master_iam_a_slave = 0;

TIMER_HANDLE Master_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 Master_obj1000 = 0x0;	/* 0 */
                    subindex Master_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 Master_obj1001 = 0x0;	/* 0 */
                    subindex Master_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 Master_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t Master_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex Master_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 Master_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 Master_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time. */
                    UNS16 Master_obj100C = 0x0;	/* 0 */
                    subindex Master_Index100C[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj100C }
                     };

/* index 0x100D :   Life Time Factor. */
                    UNS8 Master_obj100D = 0x0;	/* 0 */
                    subindex Master_Index100D[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj100D }
                     };

/* index 0x1014 :   Emergency COB ID */
                    UNS32 Master_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 Master_highestSubIndex_obj1016 = 0;
                    UNS32 Master_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 Master_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 Master_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex Master_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 Master_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x601;	/* 1537 */
                    UNS32 Master_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x581;	/* 1409 */
                    subindex Master_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 Master_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
                    UNS32 Master_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
                    UNS8 Master_obj1280_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
                    subindex Master_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 Master_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x602;	/* 1538 */
                    UNS32 Master_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 Master_obj1281_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    subindex Master_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1281 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1281_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1281_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1281_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1282 :   Client SDO 3 Parameter. */
                    UNS8 Master_highestSubIndex_obj1282 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1282_COB_ID_Client_to_Server_Transmit_SDO = 0x603;	/* 1539 */
                    UNS32 Master_obj1282_COB_ID_Server_to_Client_Receive_SDO = 0x583;	/* 1411 */
                    UNS8 Master_obj1282_Node_ID_of_the_SDO_Server = 0x3;	/* 3 */
                    subindex Master_Index1282[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1282 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1282_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1282_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1282_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1283 :   Client SDO 4 Parameter. */
                    UNS8 Master_highestSubIndex_obj1283 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1283_COB_ID_Client_to_Server_Transmit_SDO = 0x604;	/* 1540 */
                    UNS32 Master_obj1283_COB_ID_Server_to_Client_Receive_SDO = 0x584;	/* 1412 */
                    UNS8 Master_obj1283_Node_ID_of_the_SDO_Server = 0x4;	/* 4 */
                    subindex Master_Index1283[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1283 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1283_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1283_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1283_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1284 :   Client SDO 5 Parameter. */
                    UNS8 Master_highestSubIndex_obj1284 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1284_COB_ID_Client_to_Server_Transmit_SDO = 0x605;	/* 1541 */
                    UNS32 Master_obj1284_COB_ID_Server_to_Client_Receive_SDO = 0x585;	/* 1413 */
                    UNS8 Master_obj1284_Node_ID_of_the_SDO_Server = 0x5;	/* 5 */
                    subindex Master_Index1284[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1284 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1284_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1284_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1284_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 Master_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1400_COB_ID_used_by_PDO = 0x181;	/* 385 */
                    UNS8 Master_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 Master_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1401_COB_ID_used_by_PDO = 0x182;	/* 386 */
                    UNS8 Master_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 Master_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1402_COB_ID_used_by_PDO = 0x183;	/* 387 */
                    UNS8 Master_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 Master_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1403_COB_ID_used_by_PDO = 0x184;	/* 388 */
                    UNS8 Master_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1403_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1403_SYNC_start_value }
                     };

/* index 0x1404 :   Receive PDO 5 Parameter. */
                    UNS8 Master_highestSubIndex_obj1404 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1404_COB_ID_used_by_PDO = 0x185;	/* 389 */
                    UNS8 Master_obj1404_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1404_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1404_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1404_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1404_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1404[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1404 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1404_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1404_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1404_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1404_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1404_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1404_SYNC_start_value }
                     };

/* index 0x1405 :   Receive PDO 6 Parameter. */
                    UNS8 Master_highestSubIndex_obj1405 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1405_COB_ID_used_by_PDO = 0x186;	/* 390 */
                    UNS8 Master_obj1405_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1405_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1405_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1405_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1405_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1405[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1405 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1405_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1405_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1405_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1405_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1405_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1405_SYNC_start_value }
                     };

/* index 0x1406 :   Receive PDO 7 Parameter. */
                    UNS8 Master_highestSubIndex_obj1406 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1406_COB_ID_used_by_PDO = 0x187;	/* 391 */
                    UNS8 Master_obj1406_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1406_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1406_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1406_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1406_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1406[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1406 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1406_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1406_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1406_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1406_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1406_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1406_SYNC_start_value }
                     };

/* index 0x1407 :   Receive PDO 8 Parameter. */
                    UNS8 Master_highestSubIndex_obj1407 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1407_COB_ID_used_by_PDO = 0x287;	/* 647 */
                    UNS8 Master_obj1407_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1407_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1407_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1407_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1407_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1407[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1407 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1407_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1407_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1407_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1407_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1407_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1407_SYNC_start_value }
                     };

/* index 0x1408 :   Receive PDO 9 Parameter. */
                    UNS8 Master_highestSubIndex_obj1408 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1408_COB_ID_used_by_PDO = 0x188;	/* 392 */
                    UNS8 Master_obj1408_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1408_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1408_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1408_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1408_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1408[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1408 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1408_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1408_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1408_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1408_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1408_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1408_SYNC_start_value }
                     };

/* index 0x1409 :   Receive PDO 10 Parameter. */
                    UNS8 Master_highestSubIndex_obj1409 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1409_COB_ID_used_by_PDO = 0x288;	/* 648 */
                    UNS8 Master_obj1409_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1409_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1409_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1409_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1409_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1409[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1409 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1409_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1409_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1409_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1409_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1409_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1409_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 Master_highestSubIndex_obj1600 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1600[] = 
                    {
                      0x20040010,	/* 537133072 */
                      0x20280010	/* 539492368 */
                    };
                    subindex Master_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1600[1] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 Master_highestSubIndex_obj1601 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1601[] = 
                    {
                      0x20090010,	/* 537460752 */
                      0x20290010	/* 539557904 */
                    };
                    subindex Master_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1601[1] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 Master_highestSubIndex_obj1602 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1602[] = 
                    {
                      0x200E0010,	/* 537788432 */
                      0x202A0010	/* 539623440 */
                    };
                    subindex Master_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1602[1] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 Master_highestSubIndex_obj1603 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1603[] = 
                    {
                      0x20130010,	/* 538116112 */
                      0x202B0010	/* 539688976 */
                    };
                    subindex Master_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1603[1] }
                     };

/* index 0x1604 :   Receive PDO 5 Mapping. */
                    UNS8 Master_highestSubIndex_obj1604 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1604[] = 
                    {
                      0x20180010,	/* 538443792 */
                      0x20150008	/* 538247176 */
                    };
                    subindex Master_Index1604[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1604 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1604[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1604[1] }
                     };

/* index 0x1605 :   Receive PDO 6 Mapping. */
                    UNS8 Master_highestSubIndex_obj1605 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1605[] = 
                    {
                      0x201A0010,	/* 538574864 */
                      0x201B0010	/* 538640400 */
                    };
                    subindex Master_Index1605[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1605 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1605[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1605[1] }
                     };

/* index 0x1606 :   Receive PDO 7 Mapping. */
                    UNS8 Master_highestSubIndex_obj1606 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1606[] = 
                    {
                      0x20200020,	/* 538968096 */
                      0x20210020	/* 539033632 */
                    };
                    subindex Master_Index1606[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1606 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1606[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1606[1] }
                     };

/* index 0x1607 :   Receive PDO 8 Mapping. */
                    UNS8 Master_highestSubIndex_obj1607 = 1; /* number of subindex - 1*/
                    UNS32 Master_obj1607[] = 
                    {
                      0x20240020	/* 539230240 */
                    };
                    subindex Master_Index1607[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1607 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1607[0] }
                     };

/* index 0x1608 :   Receive PDO 9 Mapping. */
                    UNS8 Master_highestSubIndex_obj1608 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1608[] = 
                    {
                      0x20260020,	/* 539361312 */
                      0x20270020	/* 539426848 */
                    };
                    subindex Master_Index1608[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1608 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1608[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1608[1] }
                     };

/* index 0x1609 :   Receive PDO 10 Mapping. */
                    UNS8 Master_highestSubIndex_obj1609 = 1; /* number of subindex - 1*/
                    UNS32 Master_obj1609[] = 
                    {
                      0x20250020	/* 539295776 */
                    };
                    subindex Master_Index1609[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1609 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1609[0] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 Master_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1800_COB_ID_used_by_PDO = 0x201;	/* 513 */
                    UNS8 Master_obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Master_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Master_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 Master_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1801_COB_ID_used_by_PDO = 0x301;	/* 769 */
                    UNS8 Master_obj1801_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1801_Event_Timer = 0x15;	/* 21 */
                    UNS8 Master_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Master_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Master_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 Master_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1802_COB_ID_used_by_PDO = 0x202;	/* 514 */
                    UNS8 Master_obj1802_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Master_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Master_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 Master_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1803_COB_ID_used_by_PDO = 0x302;	/* 770 */
                    UNS8 Master_obj1803_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1803_Event_Timer = 0x24;	/* 36 */
                    UNS8 Master_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Master_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Master_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1803_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1803_SYNC_start_value }
                     };

/* index 0x1804 :   Transmit PDO 5 Parameter. */
                    UNS8 Master_highestSubIndex_obj1804 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1804_COB_ID_used_by_PDO = 0x203;	/* 515 */
                    UNS8 Master_obj1804_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj1804_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1804_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1804_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1804_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Master_Index1804_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Master_Index1804[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1804 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1804_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1804_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1804_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1804_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1804_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1804_SYNC_start_value }
                     };

/* index 0x1805 :   Transmit PDO 6 Parameter. */
                    UNS8 Master_highestSubIndex_obj1805 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1805_COB_ID_used_by_PDO = 0x303;	/* 771 */
                    UNS8 Master_obj1805_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj1805_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1805_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1805_Event_Timer = 0x21;	/* 33 */
                    UNS8 Master_obj1805_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Master_Index1805_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Master_Index1805[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1805 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1805_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1805_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1805_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1805_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1805_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1805_SYNC_start_value }
                     };

/* index 0x1806 :   Transmit PDO 7 Parameter. */
                    UNS8 Master_highestSubIndex_obj1806 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1806_COB_ID_used_by_PDO = 0x204;	/* 516 */
                    UNS8 Master_obj1806_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj1806_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1806_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1806_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1806_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Master_Index1806_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Master_Index1806[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1806 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1806_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1806_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1806_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1806_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1806_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1806_SYNC_start_value }
                     };

/* index 0x1807 :   Transmit PDO 8 Parameter. */
                    UNS8 Master_highestSubIndex_obj1807 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1807_COB_ID_used_by_PDO = 0x304;	/* 772 */
                    UNS8 Master_obj1807_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj1807_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1807_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1807_Event_Timer = 0x1B;	/* 27 */
                    UNS8 Master_obj1807_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Master_Index1807_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Master_Index1807[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1807 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1807_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1807_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1807_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1807_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1807_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1807_SYNC_start_value }
                     };

/* index 0x1808 :   Transmit PDO 9 Parameter. */
                    UNS8 Master_highestSubIndex_obj1808 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1808_COB_ID_used_by_PDO = 0x205;	/* 517 */
                    UNS8 Master_obj1808_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj1808_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1808_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1808_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1808_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Master_Index1808_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Master_Index1808[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1808 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1808_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1808_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1808_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1808_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1808_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1808_SYNC_start_value }
                     };

/* index 0x1809 :   Transmit PDO 10 Parameter. */
                    UNS8 Master_highestSubIndex_obj1809 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1809_COB_ID_used_by_PDO = 0x305;	/* 773 */
                    UNS8 Master_obj1809_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj1809_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1809_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1809_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1809_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Master_Index1809_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Master_Index1809[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1809 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1809_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1809_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1809_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1809_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1809_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1809_SYNC_start_value }
                     };

/* index 0x180A :   Transmit PDO 11 Parameter. */
                    UNS8 Master_highestSubIndex_obj180A = 6; /* number of subindex - 1*/
                    UNS32 Master_obj180A_COB_ID_used_by_PDO = 0x206;	/* 518 */
                    UNS8 Master_obj180A_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj180A_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj180A_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj180A_Event_Timer = 0x61;	/* 97 */
                    UNS8 Master_obj180A_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Master_Index180A_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Master_Index180A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj180A },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj180A_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180A_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180A_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180A_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180A_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180A_SYNC_start_value }
                     };

/* index 0x180B :   Transmit PDO 12 Parameter. */
                    UNS8 Master_highestSubIndex_obj180B = 6; /* number of subindex - 1*/
                    UNS32 Master_obj180B_COB_ID_used_by_PDO = 0x207;	/* 519 */
                    UNS8 Master_obj180B_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj180B_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj180B_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj180B_Event_Timer = 0x3E8;	/* 1000 */
                    UNS8 Master_obj180B_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Master_Index180B_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Master_Index180B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj180B },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj180B_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180B_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180B_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180B_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180B_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180B_SYNC_start_value }
                     };

/* index 0x180C :   Transmit PDO 13 Parameter. */
                    UNS8 Master_highestSubIndex_obj180C = 6; /* number of subindex - 1*/
                    UNS32 Master_obj180C_COB_ID_used_by_PDO = 0x307;	/* 775 */
                    UNS8 Master_obj180C_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj180C_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj180C_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj180C_Event_Timer = 0x3E8;	/* 1000 */
                    UNS8 Master_obj180C_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Master_Index180C_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Master_Index180C[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj180C },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj180C_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180C_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180C_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180C_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180C_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180C_SYNC_start_value }
                     };

/* index 0x180D :   Transmit PDO 14 Parameter. */
                    UNS8 Master_highestSubIndex_obj180D = 6; /* number of subindex - 1*/
                    UNS32 Master_obj180D_COB_ID_used_by_PDO = 0x306;	/* 774 */
                    UNS8 Master_obj180D_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj180D_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj180D_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj180D_Event_Timer = 0xBB8;	/* 3000 */
                    UNS8 Master_obj180D_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Master_Index180D_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Master_Index180D[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj180D },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj180D_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180D_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180D_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180D_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180D_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180D_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A00 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1A00[] = 
                    {
                      0x20010008,	/* 536936456 */
                      0x20050010	/* 537198608 */
                    };
                    subindex Master_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[1] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A01 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1A01[] = 
                    {
                      0x20020020,	/* 537002016 */
                      0x20030020	/* 537067552 */
                    };
                    subindex Master_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A01[1] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A02 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1A02[] = 
                    {
                      0x20060008,	/* 537264136 */
                      0x200A0010	/* 537526288 */
                    };
                    subindex Master_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A02[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A02[1] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A03 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1A03[] = 
                    {
                      0x20070020,	/* 537329696 */
                      0x20080020	/* 537395232 */
                    };
                    subindex Master_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A03[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A03[1] }
                     };

/* index 0x1A04 :   Transmit PDO 5 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A04 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1A04[] = 
                    {
                      0x200B0008,	/* 537591816 */
                      0x200F0010	/* 537853968 */
                    };
                    subindex Master_Index1A04[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A04 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A04[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A04[1] }
                     };

/* index 0x1A05 :   Transmit PDO 6 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A05 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1A05[] = 
                    {
                      0x200C0020,	/* 537657376 */
                      0x200D0020	/* 537722912 */
                    };
                    subindex Master_Index1A05[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A05 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A05[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A05[1] }
                     };

/* index 0x1A06 :   Transmit PDO 7 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A06 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1A06[] = 
                    {
                      0x20100008,	/* 537919496 */
                      0x20140010	/* 538181648 */
                    };
                    subindex Master_Index1A06[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A06 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A06[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A06[1] }
                     };

/* index 0x1A07 :   Transmit PDO 8 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A07 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1A07[] = 
                    {
                      0x20110020,	/* 537985056 */
                      0x20120020	/* 538050592 */
                    };
                    subindex Master_Index1A07[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A07 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A07[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A07[1] }
                     };

/* index 0x1A08 :   Transmit PDO 9 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A08 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1A08[] = 
                    {
                      0x20150008,	/* 538247176 */
                      0x20190010	/* 538509328 */
                    };
                    subindex Master_Index1A08[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A08 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A08[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A08[1] }
                     };

/* index 0x1A09 :   Transmit PDO 10 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A09 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1A09[] = 
                    {
                      0x20160020,	/* 538312736 */
                      0x20170020	/* 538378272 */
                    };
                    subindex Master_Index1A09[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A09 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A09[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A09[1] }
                     };

/* index 0x1A0A :   Transmit PDO 11 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A0A = 1; /* number of subindex - 1*/
                    UNS32 Master_obj1A0A[] = 
                    {
                      0x201C0020	/* 538705952 */
                    };
                    subindex Master_Index1A0A[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A0A },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A0A[0] }
                     };

/* index 0x1A0B :   Transmit PDO 12 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A0B = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1A0B[] = 
                    {
                      0x201E0020,	/* 538837024 */
                      0x201F0020	/* 538902560 */
                    };
                    subindex Master_Index1A0B[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A0B },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A0B[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A0B[1] }
                     };

/* index 0x1A0C :   Transmit PDO 13 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A0C = 1; /* number of subindex - 1*/
                    UNS32 Master_obj1A0C[] = 
                    {
                      0x201D0020	/* 538771488 */
                    };
                    subindex Master_Index1A0C[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A0C },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A0C[0] }
                     };

/* index 0x1A0D :   Transmit PDO 14 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A0D = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1A0D[] = 
                    {
                      0x20220010,	/* 539099152 */
                      0x20230008	/* 539164680 */
                    };
                    subindex Master_Index1A0D[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A0D },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A0D[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A0D[1] }
                     };

/* index 0x2001 :   Mapped variable mX_modes */
                    subindex Master_Index2001[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&mX_modes }
                     };

/* index 0x2002 :   Mapped variable mX_position */
                    subindex Master_Index2002[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&mX_position }
                     };

/* index 0x2003 :   Mapped variable mX_velocity */
                    subindex Master_Index2003[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&mX_velocity }
                     };

/* index 0x2004 :   Mapped variable mX_status_word */
                    subindex Master_Index2004[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&mX_status_word }
                     };

/* index 0x2005 :   Mapped variable mX_control_word */
                    subindex Master_Index2005[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&mX_control_word }
                     };

/* index 0x2006 :   Mapped variable mY_modes */
                    subindex Master_Index2006[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&mY_modes }
                     };

/* index 0x2007 :   Mapped variable mY_position */
                    subindex Master_Index2007[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&mY_position }
                     };

/* index 0x2008 :   Mapped variable mY_velocity */
                    subindex Master_Index2008[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&mY_velocity }
                     };

/* index 0x2009 :   Mapped variable mY_status_word */
                    subindex Master_Index2009[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&mY_status_word }
                     };

/* index 0x200A :   Mapped variable mY_control_word */
                    subindex Master_Index200A[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&mY_control_word }
                     };

/* index 0x200B :   Mapped variable mZ_modes */
                    subindex Master_Index200B[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&mZ_modes }
                     };

/* index 0x200C :   Mapped variable mZ_position */
                    subindex Master_Index200C[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&mZ_position }
                     };

/* index 0x200D :   Mapped variable mZ_velocity */
                    subindex Master_Index200D[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&mZ_velocity }
                     };

/* index 0x200E :   Mapped variable mZ_status_word */
                    subindex Master_Index200E[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&mZ_status_word }
                     };

/* index 0x200F :   Mapped variable mZ_control_word */
                    subindex Master_Index200F[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&mZ_control_word }
                     };

/* index 0x2010 :   Mapped variable mE_modes */
                    subindex Master_Index2010[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&mE_modes }
                     };

/* index 0x2011 :   Mapped variable mE_position */
                    subindex Master_Index2011[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&mE_position }
                     };

/* index 0x2012 :   Mapped variable mE_velocity */
                    subindex Master_Index2012[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&mE_velocity }
                     };

/* index 0x2013 :   Mapped variable mE_status_word */
                    subindex Master_Index2013[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&mE_status_word }
                     };

/* index 0x2014 :   Mapped variable mE_control_word */
                    subindex Master_Index2014[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&mE_control_word }
                     };

/* index 0x2015 :   Mapped variable mT_modes */
                    subindex Master_Index2015[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&mT_modes }
                     };

/* index 0x2016 :   Mapped variable mT_position */
                    subindex Master_Index2016[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&mT_position }
                     };

/* index 0x2017 :   Mapped variable mT_velocity */
                    subindex Master_Index2017[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&mT_velocity }
                     };

/* index 0x2018 :   Mapped variable mT_status_word */
                    subindex Master_Index2018[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&mT_status_word }
                     };

/* index 0x2019 :   Mapped variable mT_control_word */
                    subindex Master_Index2019[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&mT_control_word }
                     };

/* index 0x201A :   Mapped variable photometer_ch0 */
                    subindex Master_Index201A[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&photometer_ch0 }
                     };

/* index 0x201B :   Mapped variable photometer_ch1 */
                    subindex Master_Index201B[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&photometer_ch1 }
                     };

/* index 0x201C :   Mapped variable photometer_led */
                    subindex Master_Index201C[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&photometer_led }
                     };

/* index 0x201D :   Mapped variable TEMP_control_word */
                    subindex Master_Index201D[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TEMP_control_word }
                     };

/* index 0x201E :   Mapped variable heating_target */
                    subindex Master_Index201E[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&heating_target }
                     };

/* index 0x201F :   Mapped variable refrigeration_target */
                    subindex Master_Index201F[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&refrigeration_target }
                     };

/* index 0x2020 :   Mapped variable current_heating */
                    subindex Master_Index2020[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&current_heating }
                     };

/* index 0x2021 :   Mapped variable current_refrigeration */
                    subindex Master_Index2021[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&current_refrigeration }
                     };

/* index 0x2022 :   Mapped variable photometer_rate */
                    subindex Master_Index2022[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&photometer_rate }
                     };

/* index 0x2023 :   Mapped variable photometer_gain */
                    subindex Master_Index2023[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&photometer_gain }
                     };

/* index 0x2024 :   Mapped variable TEMP_status_word */
                    subindex Master_Index2024[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TEMP_status_word }
                     };

/* index 0x2025 :   Mapped variable weight_clean_water */
                    subindex Master_Index2025[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&weight_clean_water }
                     };

/* index 0x2026 :   Mapped variable weight_buff_liq */
                    subindex Master_Index2026[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&weight_buff_liq }
                     };

/* index 0x2027 :   Mapped variable weight_waste_liq */
                    subindex Master_Index2027[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&weight_waste_liq }
                     };

/* index 0x2028 :   Mapped variable mX_Current_actual */
                    subindex Master_Index2028[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&mX_Current_actual }
                     };

/* index 0x2029 :   Mapped variable mY_Current_actual */
                    subindex Master_Index2029[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&mY_Current_actual }
                     };

/* index 0x202A :   Mapped variable mZ_Current_actual */
                    subindex Master_Index202A[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&mZ_Current_actual }
                     };

/* index 0x202B :   Mapped variable mB_Current_actual */
                    subindex Master_Index202B[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&mB_Current_actual }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable Master_objdict[] = 
{
  { (subindex*)Master_Index1000,sizeof(Master_Index1000)/sizeof(Master_Index1000[0]), 0x1000},
  { (subindex*)Master_Index1001,sizeof(Master_Index1001)/sizeof(Master_Index1001[0]), 0x1001},
  { (subindex*)Master_Index100C,sizeof(Master_Index100C)/sizeof(Master_Index100C[0]), 0x100C},
  { (subindex*)Master_Index100D,sizeof(Master_Index100D)/sizeof(Master_Index100D[0]), 0x100D},
  { (subindex*)Master_Index1018,sizeof(Master_Index1018)/sizeof(Master_Index1018[0]), 0x1018},
  { (subindex*)Master_Index1200,sizeof(Master_Index1200)/sizeof(Master_Index1200[0]), 0x1200},
  { (subindex*)Master_Index1280,sizeof(Master_Index1280)/sizeof(Master_Index1280[0]), 0x1280},
  { (subindex*)Master_Index1281,sizeof(Master_Index1281)/sizeof(Master_Index1281[0]), 0x1281},
  { (subindex*)Master_Index1282,sizeof(Master_Index1282)/sizeof(Master_Index1282[0]), 0x1282},
  { (subindex*)Master_Index1283,sizeof(Master_Index1283)/sizeof(Master_Index1283[0]), 0x1283},
  { (subindex*)Master_Index1284,sizeof(Master_Index1284)/sizeof(Master_Index1284[0]), 0x1284},
  { (subindex*)Master_Index1400,sizeof(Master_Index1400)/sizeof(Master_Index1400[0]), 0x1400},
  { (subindex*)Master_Index1401,sizeof(Master_Index1401)/sizeof(Master_Index1401[0]), 0x1401},
  { (subindex*)Master_Index1402,sizeof(Master_Index1402)/sizeof(Master_Index1402[0]), 0x1402},
  { (subindex*)Master_Index1403,sizeof(Master_Index1403)/sizeof(Master_Index1403[0]), 0x1403},
  { (subindex*)Master_Index1404,sizeof(Master_Index1404)/sizeof(Master_Index1404[0]), 0x1404},
  { (subindex*)Master_Index1405,sizeof(Master_Index1405)/sizeof(Master_Index1405[0]), 0x1405},
  { (subindex*)Master_Index1406,sizeof(Master_Index1406)/sizeof(Master_Index1406[0]), 0x1406},
  { (subindex*)Master_Index1407,sizeof(Master_Index1407)/sizeof(Master_Index1407[0]), 0x1407},
  { (subindex*)Master_Index1408,sizeof(Master_Index1408)/sizeof(Master_Index1408[0]), 0x1408},
  { (subindex*)Master_Index1409,sizeof(Master_Index1409)/sizeof(Master_Index1409[0]), 0x1409},
  { (subindex*)Master_Index1600,sizeof(Master_Index1600)/sizeof(Master_Index1600[0]), 0x1600},
  { (subindex*)Master_Index1601,sizeof(Master_Index1601)/sizeof(Master_Index1601[0]), 0x1601},
  { (subindex*)Master_Index1602,sizeof(Master_Index1602)/sizeof(Master_Index1602[0]), 0x1602},
  { (subindex*)Master_Index1603,sizeof(Master_Index1603)/sizeof(Master_Index1603[0]), 0x1603},
  { (subindex*)Master_Index1604,sizeof(Master_Index1604)/sizeof(Master_Index1604[0]), 0x1604},
  { (subindex*)Master_Index1605,sizeof(Master_Index1605)/sizeof(Master_Index1605[0]), 0x1605},
  { (subindex*)Master_Index1606,sizeof(Master_Index1606)/sizeof(Master_Index1606[0]), 0x1606},
  { (subindex*)Master_Index1607,sizeof(Master_Index1607)/sizeof(Master_Index1607[0]), 0x1607},
  { (subindex*)Master_Index1608,sizeof(Master_Index1608)/sizeof(Master_Index1608[0]), 0x1608},
  { (subindex*)Master_Index1609,sizeof(Master_Index1609)/sizeof(Master_Index1609[0]), 0x1609},
  { (subindex*)Master_Index1800,sizeof(Master_Index1800)/sizeof(Master_Index1800[0]), 0x1800},
  { (subindex*)Master_Index1801,sizeof(Master_Index1801)/sizeof(Master_Index1801[0]), 0x1801},
  { (subindex*)Master_Index1802,sizeof(Master_Index1802)/sizeof(Master_Index1802[0]), 0x1802},
  { (subindex*)Master_Index1803,sizeof(Master_Index1803)/sizeof(Master_Index1803[0]), 0x1803},
  { (subindex*)Master_Index1804,sizeof(Master_Index1804)/sizeof(Master_Index1804[0]), 0x1804},
  { (subindex*)Master_Index1805,sizeof(Master_Index1805)/sizeof(Master_Index1805[0]), 0x1805},
  { (subindex*)Master_Index1806,sizeof(Master_Index1806)/sizeof(Master_Index1806[0]), 0x1806},
  { (subindex*)Master_Index1807,sizeof(Master_Index1807)/sizeof(Master_Index1807[0]), 0x1807},
  { (subindex*)Master_Index1808,sizeof(Master_Index1808)/sizeof(Master_Index1808[0]), 0x1808},
  { (subindex*)Master_Index1809,sizeof(Master_Index1809)/sizeof(Master_Index1809[0]), 0x1809},
  { (subindex*)Master_Index180A,sizeof(Master_Index180A)/sizeof(Master_Index180A[0]), 0x180A},
  { (subindex*)Master_Index180B,sizeof(Master_Index180B)/sizeof(Master_Index180B[0]), 0x180B},
  { (subindex*)Master_Index180C,sizeof(Master_Index180C)/sizeof(Master_Index180C[0]), 0x180C},
  { (subindex*)Master_Index180D,sizeof(Master_Index180D)/sizeof(Master_Index180D[0]), 0x180D},
  { (subindex*)Master_Index1A00,sizeof(Master_Index1A00)/sizeof(Master_Index1A00[0]), 0x1A00},
  { (subindex*)Master_Index1A01,sizeof(Master_Index1A01)/sizeof(Master_Index1A01[0]), 0x1A01},
  { (subindex*)Master_Index1A02,sizeof(Master_Index1A02)/sizeof(Master_Index1A02[0]), 0x1A02},
  { (subindex*)Master_Index1A03,sizeof(Master_Index1A03)/sizeof(Master_Index1A03[0]), 0x1A03},
  { (subindex*)Master_Index1A04,sizeof(Master_Index1A04)/sizeof(Master_Index1A04[0]), 0x1A04},
  { (subindex*)Master_Index1A05,sizeof(Master_Index1A05)/sizeof(Master_Index1A05[0]), 0x1A05},
  { (subindex*)Master_Index1A06,sizeof(Master_Index1A06)/sizeof(Master_Index1A06[0]), 0x1A06},
  { (subindex*)Master_Index1A07,sizeof(Master_Index1A07)/sizeof(Master_Index1A07[0]), 0x1A07},
  { (subindex*)Master_Index1A08,sizeof(Master_Index1A08)/sizeof(Master_Index1A08[0]), 0x1A08},
  { (subindex*)Master_Index1A09,sizeof(Master_Index1A09)/sizeof(Master_Index1A09[0]), 0x1A09},
  { (subindex*)Master_Index1A0A,sizeof(Master_Index1A0A)/sizeof(Master_Index1A0A[0]), 0x1A0A},
  { (subindex*)Master_Index1A0B,sizeof(Master_Index1A0B)/sizeof(Master_Index1A0B[0]), 0x1A0B},
  { (subindex*)Master_Index1A0C,sizeof(Master_Index1A0C)/sizeof(Master_Index1A0C[0]), 0x1A0C},
  { (subindex*)Master_Index1A0D,sizeof(Master_Index1A0D)/sizeof(Master_Index1A0D[0]), 0x1A0D},
  { (subindex*)Master_Index2001,sizeof(Master_Index2001)/sizeof(Master_Index2001[0]), 0x2001},
  { (subindex*)Master_Index2002,sizeof(Master_Index2002)/sizeof(Master_Index2002[0]), 0x2002},
  { (subindex*)Master_Index2003,sizeof(Master_Index2003)/sizeof(Master_Index2003[0]), 0x2003},
  { (subindex*)Master_Index2004,sizeof(Master_Index2004)/sizeof(Master_Index2004[0]), 0x2004},
  { (subindex*)Master_Index2005,sizeof(Master_Index2005)/sizeof(Master_Index2005[0]), 0x2005},
  { (subindex*)Master_Index2006,sizeof(Master_Index2006)/sizeof(Master_Index2006[0]), 0x2006},
  { (subindex*)Master_Index2007,sizeof(Master_Index2007)/sizeof(Master_Index2007[0]), 0x2007},
  { (subindex*)Master_Index2008,sizeof(Master_Index2008)/sizeof(Master_Index2008[0]), 0x2008},
  { (subindex*)Master_Index2009,sizeof(Master_Index2009)/sizeof(Master_Index2009[0]), 0x2009},
  { (subindex*)Master_Index200A,sizeof(Master_Index200A)/sizeof(Master_Index200A[0]), 0x200A},
  { (subindex*)Master_Index200B,sizeof(Master_Index200B)/sizeof(Master_Index200B[0]), 0x200B},
  { (subindex*)Master_Index200C,sizeof(Master_Index200C)/sizeof(Master_Index200C[0]), 0x200C},
  { (subindex*)Master_Index200D,sizeof(Master_Index200D)/sizeof(Master_Index200D[0]), 0x200D},
  { (subindex*)Master_Index200E,sizeof(Master_Index200E)/sizeof(Master_Index200E[0]), 0x200E},
  { (subindex*)Master_Index200F,sizeof(Master_Index200F)/sizeof(Master_Index200F[0]), 0x200F},
  { (subindex*)Master_Index2010,sizeof(Master_Index2010)/sizeof(Master_Index2010[0]), 0x2010},
  { (subindex*)Master_Index2011,sizeof(Master_Index2011)/sizeof(Master_Index2011[0]), 0x2011},
  { (subindex*)Master_Index2012,sizeof(Master_Index2012)/sizeof(Master_Index2012[0]), 0x2012},
  { (subindex*)Master_Index2013,sizeof(Master_Index2013)/sizeof(Master_Index2013[0]), 0x2013},
  { (subindex*)Master_Index2014,sizeof(Master_Index2014)/sizeof(Master_Index2014[0]), 0x2014},
  { (subindex*)Master_Index2015,sizeof(Master_Index2015)/sizeof(Master_Index2015[0]), 0x2015},
  { (subindex*)Master_Index2016,sizeof(Master_Index2016)/sizeof(Master_Index2016[0]), 0x2016},
  { (subindex*)Master_Index2017,sizeof(Master_Index2017)/sizeof(Master_Index2017[0]), 0x2017},
  { (subindex*)Master_Index2018,sizeof(Master_Index2018)/sizeof(Master_Index2018[0]), 0x2018},
  { (subindex*)Master_Index2019,sizeof(Master_Index2019)/sizeof(Master_Index2019[0]), 0x2019},
  { (subindex*)Master_Index201A,sizeof(Master_Index201A)/sizeof(Master_Index201A[0]), 0x201A},
  { (subindex*)Master_Index201B,sizeof(Master_Index201B)/sizeof(Master_Index201B[0]), 0x201B},
  { (subindex*)Master_Index201C,sizeof(Master_Index201C)/sizeof(Master_Index201C[0]), 0x201C},
  { (subindex*)Master_Index201D,sizeof(Master_Index201D)/sizeof(Master_Index201D[0]), 0x201D},
  { (subindex*)Master_Index201E,sizeof(Master_Index201E)/sizeof(Master_Index201E[0]), 0x201E},
  { (subindex*)Master_Index201F,sizeof(Master_Index201F)/sizeof(Master_Index201F[0]), 0x201F},
  { (subindex*)Master_Index2020,sizeof(Master_Index2020)/sizeof(Master_Index2020[0]), 0x2020},
  { (subindex*)Master_Index2021,sizeof(Master_Index2021)/sizeof(Master_Index2021[0]), 0x2021},
  { (subindex*)Master_Index2022,sizeof(Master_Index2022)/sizeof(Master_Index2022[0]), 0x2022},
  { (subindex*)Master_Index2023,sizeof(Master_Index2023)/sizeof(Master_Index2023[0]), 0x2023},
  { (subindex*)Master_Index2024,sizeof(Master_Index2024)/sizeof(Master_Index2024[0]), 0x2024},
  { (subindex*)Master_Index2025,sizeof(Master_Index2025)/sizeof(Master_Index2025[0]), 0x2025},
  { (subindex*)Master_Index2026,sizeof(Master_Index2026)/sizeof(Master_Index2026[0]), 0x2026},
  { (subindex*)Master_Index2027,sizeof(Master_Index2027)/sizeof(Master_Index2027[0]), 0x2027},
  { (subindex*)Master_Index2028,sizeof(Master_Index2028)/sizeof(Master_Index2028[0]), 0x2028},
  { (subindex*)Master_Index2029,sizeof(Master_Index2029)/sizeof(Master_Index2029[0]), 0x2029},
  { (subindex*)Master_Index202A,sizeof(Master_Index202A)/sizeof(Master_Index202A[0]), 0x202A},
  { (subindex*)Master_Index202B,sizeof(Master_Index202B)/sizeof(Master_Index202B[0]), 0x202B},
};

const indextable * Master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x100C: i = 2;break;
		case 0x100D: i = 3;break;
		case 0x1018: i = 4;break;
		case 0x1200: i = 5;break;
		case 0x1280: i = 6;break;
		case 0x1281: i = 7;break;
		case 0x1282: i = 8;break;
		case 0x1283: i = 9;break;
		case 0x1284: i = 10;break;
		case 0x1400: i = 11;break;
		case 0x1401: i = 12;break;
		case 0x1402: i = 13;break;
		case 0x1403: i = 14;break;
		case 0x1404: i = 15;break;
		case 0x1405: i = 16;break;
		case 0x1406: i = 17;break;
		case 0x1407: i = 18;break;
		case 0x1408: i = 19;break;
		case 0x1409: i = 20;break;
		case 0x1600: i = 21;break;
		case 0x1601: i = 22;break;
		case 0x1602: i = 23;break;
		case 0x1603: i = 24;break;
		case 0x1604: i = 25;break;
		case 0x1605: i = 26;break;
		case 0x1606: i = 27;break;
		case 0x1607: i = 28;break;
		case 0x1608: i = 29;break;
		case 0x1609: i = 30;break;
		case 0x1800: i = 31;*callbacks = Master_Index1800_callbacks; break;
		case 0x1801: i = 32;*callbacks = Master_Index1801_callbacks; break;
		case 0x1802: i = 33;*callbacks = Master_Index1802_callbacks; break;
		case 0x1803: i = 34;*callbacks = Master_Index1803_callbacks; break;
		case 0x1804: i = 35;*callbacks = Master_Index1804_callbacks; break;
		case 0x1805: i = 36;*callbacks = Master_Index1805_callbacks; break;
		case 0x1806: i = 37;*callbacks = Master_Index1806_callbacks; break;
		case 0x1807: i = 38;*callbacks = Master_Index1807_callbacks; break;
		case 0x1808: i = 39;*callbacks = Master_Index1808_callbacks; break;
		case 0x1809: i = 40;*callbacks = Master_Index1809_callbacks; break;
		case 0x180A: i = 41;*callbacks = Master_Index180A_callbacks; break;
		case 0x180B: i = 42;*callbacks = Master_Index180B_callbacks; break;
		case 0x180C: i = 43;*callbacks = Master_Index180C_callbacks; break;
		case 0x180D: i = 44;*callbacks = Master_Index180D_callbacks; break;
		case 0x1A00: i = 45;break;
		case 0x1A01: i = 46;break;
		case 0x1A02: i = 47;break;
		case 0x1A03: i = 48;break;
		case 0x1A04: i = 49;break;
		case 0x1A05: i = 50;break;
		case 0x1A06: i = 51;break;
		case 0x1A07: i = 52;break;
		case 0x1A08: i = 53;break;
		case 0x1A09: i = 54;break;
		case 0x1A0A: i = 55;break;
		case 0x1A0B: i = 56;break;
		case 0x1A0C: i = 57;break;
		case 0x1A0D: i = 58;break;
		case 0x2001: i = 59;break;
		case 0x2002: i = 60;break;
		case 0x2003: i = 61;break;
		case 0x2004: i = 62;break;
		case 0x2005: i = 63;break;
		case 0x2006: i = 64;break;
		case 0x2007: i = 65;break;
		case 0x2008: i = 66;break;
		case 0x2009: i = 67;break;
		case 0x200A: i = 68;break;
		case 0x200B: i = 69;break;
		case 0x200C: i = 70;break;
		case 0x200D: i = 71;break;
		case 0x200E: i = 72;break;
		case 0x200F: i = 73;break;
		case 0x2010: i = 74;break;
		case 0x2011: i = 75;break;
		case 0x2012: i = 76;break;
		case 0x2013: i = 77;break;
		case 0x2014: i = 78;break;
		case 0x2015: i = 79;break;
		case 0x2016: i = 80;break;
		case 0x2017: i = 81;break;
		case 0x2018: i = 82;break;
		case 0x2019: i = 83;break;
		case 0x201A: i = 84;break;
		case 0x201B: i = 85;break;
		case 0x201C: i = 86;break;
		case 0x201D: i = 87;break;
		case 0x201E: i = 88;break;
		case 0x201F: i = 89;break;
		case 0x2020: i = 90;break;
		case 0x2021: i = 91;break;
		case 0x2022: i = 92;break;
		case 0x2023: i = 93;break;
		case 0x2024: i = 94;break;
		case 0x2025: i = 95;break;
		case 0x2026: i = 96;break;
		case 0x2027: i = 97;break;
		case 0x2028: i = 98;break;
		case 0x2029: i = 99;break;
		case 0x202A: i = 100;break;
		case 0x202B: i = 101;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &Master_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status Master_PDO_status[14] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index Master_firstIndex = {
  5, /* SDO_SVR */
  6, /* SDO_CLT */
  11, /* PDO_RCV */
  21, /* PDO_RCV_MAP */
  31, /* PDO_TRS */
  45 /* PDO_TRS_MAP */
};

const quick_index Master_lastIndex = {
  5, /* SDO_SVR */
  10, /* SDO_CLT */
  20, /* PDO_RCV */
  30, /* PDO_RCV_MAP */
  44, /* PDO_TRS */
  58 /* PDO_TRS_MAP */
};

const UNS16 Master_ObjdictSize = sizeof(Master_objdict)/sizeof(Master_objdict[0]); 

CO_Data Master_Data = CANOPEN_NODE_DATA_INITIALIZER(Master);

